# Generated by Django 4.2.6 on 2023-10-07 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbook', '0002_alter_category_image_alter_category_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Количество лайков')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Количество комментарий')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('file', models.FileField(blank=True, upload_to='projects/uploads/')),
                ('categories', models.ManyToManyField(to='handbook.category', verbose_name='Категории')),
                ('images', models.ManyToManyField(blank=True, to='gallery.image', verbose_name='Изображения')),
                ('members', models.ManyToManyField(blank=True, related_name='projects_contributed', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('tags', models.ManyToManyField(blank=True, to='handbook.tag', verbose_name='Теги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-id',),
            },
        ),
    ]
