# Generated by Django 4.2.6 on 2023-10-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_alter_category_image_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
