# Generated by Django 4.2.6 on 2023-10-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0004_favorites_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('created_at',), 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
    ]
