# Generated by Django 4.2.6 on 2023-10-07 08:41

from django.db import migrations, models
import django.db.models.deletion
import src.apps.gallery.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('name', models.CharField(max_length=200, verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('original', models.ImageField(blank=True, null=True, upload_to='images/original/', verbose_name='Оригинал')),
                ('original_url', models.URLField(blank=True, max_length=1000, null=True, validators=[src.apps.gallery.utils.validate_image_url], verbose_name='URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnail/', verbose_name='Миниатюрка')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.folder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
