# Generated by Django 4.2.6 on 2023-10-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientProfile',
            new_name='UserProfile',
        ),
    ]
