# Generated by Django 4.2.6 on 2023-10-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_clientprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
