# Generated by Django 4.2.6 on 2023-10-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
        ('accounts', '0003_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categories',
            field=models.ManyToManyField(to='handbook.category', verbose_name='Категории'),
        ),
    ]
